name: ci-for-pull-request
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: ci
        run: npm ci
      - name: Build Check
        run: npm run build